name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: cargo test -- --nocapture
    - name: Format
      run: cargo fmt -- --check 