name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test
      env: 
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USERNAME: zower98
        REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
      run: cargo test
    - name: Format
      run: cargo fmt -- --check 